apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example
  namespace: oih-dev-ns
  labels:
    app: mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard